apiVersion: v1
summary: Stop untagged EC2 instances
description: This workflow looks at all of the EC2 instances in a given account and region and stops the ones that are untagged. Requires an AWS account with permissions to delete stop EC2 instances.
homepage: https://github.com/puppetlabs/relay-workflows/tree/master/ec2-stop-untagged-instances
tags:
  - compliance

# Uncomment out this trigger to run this workflow hourly.
# triggers:
# - name: schedule
#   source:
#     type: schedule
#     schedule: '0 * * * *'
#   binding:
#     parameters:
#       awsRegion: us-east-1
#       dryRun: true

parameters:
  awsRegion:
    description: The AWS region to run in
    default: us-east-1
  dryRun:
    description: True if you dont want to actually delete the resources. Use this to test the workflow and ensure it is behaving as expected.
    default: 'true'

steps:
- name: describe-instances
  image: relaysh/aws-ec2-step-instances-describe
  spec:
    aws: &aws
      connection: !Connection { type: aws, name: my-aws-account }
      region: !Parameter awsRegion
- name: filter-instances
  image: relaysh/core:latest-python
  spec:
    instances: !Output {from: describe-instances, name: instances}
  inputFile: https://raw.githubusercontent.com/puppetlabs/relay-workflows/master/ec2-stop-untagged-instances/filter-instances.py
- name: approval
  description: Wait for approval to stop instances
  type: approval
  dependsOn: filter-instances
  when:
    - !Fn.equals [!Parameter dryRun, 'false']
- name: stop-instances
  dependsOn: approval
  image: relaysh/aws-ec2-step-instances-stop
  when:
    - !Fn.equals [!Parameter dryRun, 'false']
  spec:
    aws: *aws
    instanceIDs: !Output {from: filter-instances, name: instanceIDs}
